name: Deploy to GitHub Pages

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Generate token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Get SparkFun Doc repos
        run: gh search repos topic:sparkfun-tutorial --owner sparkfun --visibility public --sort updated --order desc --limit 1000 --json name,url,homepage,description,updatedAt > sfe_raw.json

      - name: Process repo data and get social images
        env:
          SFE_DOCS_BUILD_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          python ./sfe_repo_info.py ./sfe_raw.json ./src/data/sfe_data.json --tags-file=./src/data/sfe_tags.json --create-sitemap --site-dest=static --skip-images

      #   # Make sure the action permission for the repo has read and write set for the GITHUB_TOKEN secret, otherwise the commit and push steps will fail with a permissions error
      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add ./static/sitemap.xml ./src/data/sfe_data.json ./static/img/sparkfun/*
          git diff --staged --quiet || git commit -m "Update processed repo data and images"
          git push

      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
